[tools]
stylua = "latest"
"cargo:vimcats" = { version = "latest", features = "cli" }

[tasks.fmt]
run = "stylua lua/"

[tasks.doc]
run = '''
mkdir -p doc
vimcats -f -i 2 --layout mini:2 lua/mappet.lua > doc/mappet.txt
'''
