[tools]
neovim = "0.12"
stylua = "latest"
"cargo:vimcats" = { version = "latest", features = "cli" }
"aqua:LuaLS/lua-language-server" = "latest"

[tasks.lint]
alias = "l"
depends = "lint:*"

[tasks."lint:format"]
run = "stylua --check lua/"

[tasks."lint:lsp"]
run = '''
VIMRUNTIME=$(nvim --headless --clean -u NONE --noplugin "+lua io.write(vim.env.VIMRUNTIME)" +qa) \
  lua-language-server --check . --checklevel=Warning --configpath luarc.json
'''

[tasks.format]
alias = "f"
run = "stylua lua/"

[tasks.doc]
run = '''
mkdir -p doc
vimcats -f -i 2 --layout mini:2 lua/mappet.lua > doc/mappet.txt
'''

[tasks.test]
alias = "t"
depends = ["dev-deps"]
run = "nvim --headless --noplugin -u ./tests/run.lua"

[tasks.dev-deps]
run = '''
mkdir -p deps
if [ ! -d deps/mini.test/.git ]; then
  git clone \
    --filter=blob:none \
    --branch stable \
    --depth 1 \
    https://github.com/nvim-mini/mini.test \
    deps/mini.test
fi
'''
